export const newTestamentEvents = [
  {
    Year: '',
    End_Year: '',
    Headline: 'Take a journey through the Biblical Timeline ',
    Text: 'Welcome to the TBS Timeline. Click the NEXT arrow to see the beginning of our timeline, the time of Adam which starts at 4000 BC est. Or you can click any event on the timeline to learn about it.',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: 'title',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-4',
    End_Year: '',
    Headline: "Jesus' Birth",
    Text: 'The magi have arrived in Jerusalem, asking about the newborn king of the Jews so that they might locate and worship him. Herod the king became aware of their arrival to the city and their questions. Being ever mindful of any threat to his power, Herod is deeply troubled by the magi’s questions. When Herod was troubled, everyone felt it. So all Jerusalem was troubled with him. Herod might have keenly felt the magi’s claim that there was a king other than him, because he was in fact only “half-Jew.” His father, Antipater, was an Edomite.\nEven if the magi’s claim was not true, if the expectant people under Herod’s rule put stock in the magi’s words and believed their claim that the King of the Jews was recently born, it could lead to an uprising, and the end of his reign and dynasty. The magi’s unexpected arrival and astonishing announcement that a Jewish King had been born was the talk of Jerusalem. No doubt many were hopeful that this might mean the coming of the Messiah. It did not take much political calculus for Herod to recognize that if he wanted to remain in power, he could not afford to allow these rumors to spread.',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '8',
    End_Year: '',
    Headline: 'Jesus interacts with the elders in the Temple',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '27',
    End_Year: '',
    Headline: 'Jesus begins His ministry',
    Text: "Jesus's ministry begins with his baptism by his cousin, John the Baptist. This baptism serves as a special anointment before the Messiah King proclaims His Kingdom. In this regard, Jesus is like Jesse’s son, David, who is anointed as king by the prophet Samuel (1 Samuel 16:1-13). In this case, John the Baptist is the prophet. Rather than anointing Jesus with oil, which would be a sign that He was being appointed king, Jesus is baptized. This might be an indication that Jesus’ initial ministry will have a spiritual rather than earthly focus.",
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '30',
    End_Year: '',
    Headline: "Jesus' Crucifixion",
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/crucifixion.jpg',
  },
  {
    Year: '30',
    End_Year: '',
    Headline: "Jesus' Resurrection",
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background: '',
  },
  {
    Year: '34',
    End_Year: '',
    Headline: 'Saul of Tarsus (Paul) sees Jesus on the way to Damascus',
    Text: 'Paul had condoned the stoning of Stephen who was murdered for proclaiming the gospel (Acts 7) and went “house after house…dragging off men and women and would put them in prison” (Act 8:3). He was a vicious persecutor of the early Church. But while Paul was traveling to Damascus to arrest believers there and bring them to Jerusalem, Jesus appeared before him: “Suddenly a light from heaven flashed around him; and he fell to the ground and heard a voice saying to him, “Saul, Saul,* why are you persecuting Me?”  And he said, “Who are You, Lord?” And He said, “I am Jesus whom you are persecuting, but get up and enter the city, and it will be told you what you must do” (Acts 9:3b-5).\n(*Saul is Paul’s Hebrew name).',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '38',
    End_Year: '',
    Headline: 'Peter witnesses to Cornelius',
    Text: " A Roman centurion, Cornelius, a Gentile who fears God, brings Peter to his household, where Peter shares the gospel, explaining, “You yourselves know how unlawful it is for a man who is a Jew to associate with a foreigner or to visit him; and yet God has shown me that I should not call any man unholy or unclean” (Acts 10:28) Peter's witnessing to Cornelius solidifies that the gospel of Jesus was for all men, not just the Jews.",
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '55',
    End_Year: '',
    Headline: 'Paul writes to the Galatians',
    Text: 'Unlike his corrective letter to the Romans whom he had not met face-to-face (where Paul also answered slanderous charges from competing Jewish “authorities”), the Galatians were people he had personally ministered to (Acts 18:23). So while the basic arguments in Galatians and Romans have much in common, the tone of Galatians is more like a father scolding a child, whereas Paul’s letter to the Romans takes a far more diplomatic tone. Galatia likely refers to a region in what is now central Turkey. At the time Paul wrote this letter—which is often placed around 55 AD—these cities would have been Roman colonies, occupied primarily by Greek-speaking Gentiles. The region included cities mentioned on Paul’s missionary journeys in the book of Acts such as Lystra, Iconium, and Derbe. (Acts 14 and Acts 16:1-5). Paul’s disciple Timothy was from Lystra (Acts 16:1).',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '49',
    End_Year: '',
    Headline: 'Claudius expels Jews from Rome',
    Text: 'After issues with riots between Greeks and Jews, Claudius expelled Jews from Rome. Since Christians were still considered part of the Jewish faith by the Roman Empire, they were expelled too. Priscilla and Aquila -- Paul’s co-laborers in founding the church in Rome -- were brought to the knowledge of Jesus while they were refugees from persecution under the emperor Claudius, having fled Rome for a time (Acts 18:2; Romans 16:3).',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '70',
    End_Year: '',
    Headline: 'Roman Conquest of Jerusalem',
    Text: 'Rome sieged and destroyed Jerusalem in 70 AD during a period commonly referred to as the “Jewish Wars.”\nThe party of Jewish Zealots waged the Jewish wars that began in AD 66 and ended in AD 73. The headquarters of the Zealots was in Gamla, a fortress town about five miles from the north shore of the Sea of Galilee. The Romans placed a legion on the eastern shore of Galilee, perhaps because of the presence of the Zealots. It could be that Simon was a member of that party, in which case he would have been part of a group of twelve that included a tax collector who worked for the Romans as well as a Zealot who was dedicated to eliminating the Romans. During the Jewish Wars, the Zealots at Gamla jumped from the cliff on which the city was located rather than be captured by the Romans. It is estimated that between three and four thousand lept to their death. Jerusalem was razed to the ground as a part of this war in 70 AD. The final stand was made by the Zealots at Masada, when roughly a thousand Zealots took their lives rather than be captured by the Romans.',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/Roberts_Siege_and_Destruction_of_Jerusalem.jpeg',
  },
  {
    Year: '95',
    End_Year: '',
    Headline: 'John exiled to Patmos ',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
]
