export const newTestamentBooks = [
  {
    Year: '',
    End_Year: '',
    Headline: '',
    Text: 'Welcome to the TBS Timeline. Click the NEXT arrow to see the beginning of this timeline. Or you can click any book on the timeline to learn about it. ',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: 'title',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '44',
    End_Year: '',
    Headline: 'James',
    Text: 'James was written by the human half-brother of Jesus who identifies himself simply as a servant of God and the Lord Jesus Christ. He writes to the Jewish believers who are scattered abroad in the Greco-Roman world of the first century BC. The book of James is similar to Wisdom Literature like Proverbs, Ecclesiastes, and the Sermon on the Mount. The author employs a series of short messages which give advice, counsel, and wisdom to the readers.\n\nThe audience is clearly those who are already in the faith and are addressed as ‘brothers,’ which is the Greek word “adelphos.” “Adelphos” includes all in Christ, without distinction as to gender or station in life, so brothers and sisters without ranks. That James is addressing those who have already been adopted into God’s family by faith in Christ is abundantly clear by the term ‘brother’ (see James 1:2, 9, 16, 19; 2:1, 5, 14, 15; 3:1, 10, 12; 4:11; 5:7, 9, 10, 12, and 19). James is not addressing the ‘lost’ to become found, but rather is telling the ‘found’ how to grow, gain the greatest reward and fulfillment from life and not lose their way.',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '50',
    End_Year: '',
    Headline: 'Matthew',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '45',
    End_Year: '',
    Headline: 'Mark',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '60',
    End_Year: '',
    Headline: 'Luke',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '80',
    End_Year: '',
    Headline: 'John',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '62',
    End_Year: '',
    Headline: 'Acts',
    Text: 'Luke begins the sequel to his Gospel. These are the Acts of the Apostles and of the Holy Spirit. Jesus Christ has resurrected and is about to return to Heaven. He tells His disciples to wait in Jerusalem for the Holy Spirit to arrive. The Holy Spirit will empower them and lead them through the trials they will face. The disciples wonder when the Kingdom of God will be established, but Jesus tells them that it is not their business to know. Their business is to tell the whole world about Jesus’s death and resurrection. ',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '56',
    End_Year: '',
    Headline: 'Romans',
    Text: 'The Apostle Paul writes to the world-renowned believers in Rome, the center of the world at that time, in order to answer a slanderous charge made to them against Paul and his message. Paul’s detractors claim his emphasis on faith overturns the law. Paul says that ” just living by the law” does not achieve personal justice before God, while “just living by faith” does. Paul then demonstrates what a just life looks like: harmonious living with Jesus as the leader. Paul also makes clear the choice a believer has: to walk in faith and the power of the resurrection and experience resurrection life, or walk in sin and unnecessarily experience the negative consequences.',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '55',
    End_Year: '',
    Headline: '1 Corinthians',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '56',
    End_Year: '',
    Headline: '2 Corinthians',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '49',
    End_Year: '',
    Headline: 'Galatians',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '62',
    End_Year: '',
    Headline: 'Ephesians',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '61',
    End_Year: '',
    Headline: 'Philippians',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '60',
    End_Year: '',
    Headline: 'Colossians',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '51',
    End_Year: '',
    Headline: '1 Thessalonians',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '52',
    End_Year: '',
    Headline: '2 Thessalonians',
    Text: '2 Thessalonians is a follow-up letter to 1 Thessalonians. The Apostle Paul probably wrote 1 Thessalonians from the Greek city of Corinth, when Timothy came to him with news that the Thessalonians were withstanding persecution and continuing in the faith. Corinth is in southern Greece, about 350 miles south of Thessalonica, which was in Macedonia.The first letter to the Thessalonians communicated Paul’s anxiety for their spiritual wellbeing prior to hearing Timothy’s report, his joy to learn from Timothy that they were doing well, his encouragement that they increase all the more in their love for one another, some ways in which they could mature in their faith, as well as clearing up a question about Christ’s second coming. The Thessalonians were concerned that if any of them died physically before Jesus came back, they would miss out on being with Jesus. Paul answered that concern, and explicitly tells them that believers who have died will be raised back to life and will join Jesus when He returns in the air (1 Thessalonians 4:16-17).',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '63',
    End_Year: '',
    Headline: '1 Timothy',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '66',
    End_Year: '',
    Headline: '2 Timothy',
    Text: 'This letter was written by the Apostle Paul, while in prison in Rome. This was Paul’s second imprisonment. He was released from his first imprisonment, where he was under house arrest (Acts 28:30). Tradition holds that at the time of writing this, his last epistle, Paul was in Mamertine Prison, which was a “death row” prison. It is clear from the letter’s contents that Paul expects to be executed.\nHis purpose in writing this letter to his primary disciple Timothy was to bolster Timothy’s courage, and provide him with all the reasons why he too ought to embrace living life as a faithful witness who does not fear death, loss, or rejection. By application, Paul’s letter applies to any believer who desires to gain the most from their time on earth.',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '64',
    End_Year: '',
    Headline: 'Titus',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '61',
    End_Year: '',
    Headline: 'Philemon',
    Text: 'Paul and Timothy make a personal plea to Philemon, a Colossian believer whom Paul mentored into Christ. The appeal is for Philemon to forgive Onesimus, his runaway slave, who also came to Christ through Paul’s ministry. Additionally, Paul asks Philemon to send Onesimus back to him in Rome because he has been a great help to him and his ministry during his imprisonment there. Paul reminds Philemon of the forgiveness he has received, and touches upon the truth that the fundamental relationship between Philemon and Onesimus is not a temporal master-slave relationship, but as forever brothers in the family of Christ.',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '67',
    End_Year: '',
    Headline: 'Hebrews',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '65',
    End_Year: '',
    Headline: '1 Peter',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '68',
    End_Year: '',
    Headline: '2 Peter',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '90',
    End_Year: '',
    Headline: '1 John',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '92',
    End_Year: '',
    Headline: '2 John',
    Text: 'This letter is attributed to the Apostle John. He speaks not from the authority of an apostle who has seen the risen Lord, as would be his right. Rather he speaks from the position of being an elder of the church. He sends this letter ahead, expecting to be there in person soon. However, John has urgency to exhort the church to whom he writes to avoid listening to a particular group of false teachers, who are apparently deceiving, and leading people away from obeying Jesus’ command to love one another. If they allow themselves to be deceived, it could result in them losing a portion of their reward at the judgement seat of Christ. John does not desire that. Rather, he desires that their joy be made full, and they receive rewards that endure forever.',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '94',
    End_Year: '',
    Headline: '3 John',
    Text: 'This brief letter of John was apparently written and sent in haste to counter the actions and teaching of Diotrephes. John had much more to say, but wrote that he planned to visit the recipient of his letter, Gaius, and would address in person the other topics he had in mind. Nevertheless, the actions of Diotrephes apparently required an urgent and immediate response. Diotrephes was a self-serving leader who appears to have been creating a division in the church. He was not a servant leader, but was rather seeking to elevate himself above the other leaders. Further, he was forbidding the members of the church to be hospitable to traveling ministers who were ministering in the name of Jesus.\nJohn confronts Diotrephes, while being careful not to make any of the same missteps. John does not appeal to his superior authority, but rather invites the local church to make their own decision based on the facts, the testimony of reliable people, and the truth of God.',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '69',
    End_Year: '',
    Headline: 'Jude',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '95',
    End_Year: '',
    Headline: 'Revelation',
    Text: 'Revelation is a simple book with a simple message for believers: be a faithful witness and don’t fear loss, rejection, or death. For believers who heed this message, Jesus promises rewards beyond their wildest imagination. Jesus Himself is an example of one who endured great suffering through obedience, and gained the greatest of rewards. He encourages “His servants” to follow in His footsteps.',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
]
