export const oldTestamentBooks = [
  {
    Year: '-1555',
    End_Year: '',
    Headline: 'Genesis',
    Text: 'Genesis is a book about many beginnings. The beginnings of the world, the human race, sin and redemption, and the nation of Israel to name a few. In fact, the word Genesis from the Greek means “origin,” and in Hebrew it means “beginning.” The book of Genesis contains the events of the flood, tower of Babel, Sodom and Gomorrah, and the lives of the Patriarchs.\nIn the beginning, God created everything by simply speaking, “God said…and it was so” (Genesis 1:6-7, 9, 11, 14-15). This is not a scientific technical account of creation, but it shows a loving God creating a universe and mankind to rule it and fellowship with God. Man was formed especially from the ground and given the breath of life from God. The woman was made from the man’s rib (Genesis 2:7). After man fell into sin, things began to spin out of control quickly. Cain murdered his brother Abel and the human race became so violent that God decided to destroy them all with a flood. God saved one righteous man (Noah) and his family in an ark filled with animals to deliver the human race from extinction. God chose Abraham and blessed a special group of people named “Israel.” God began to unfold a plan of salvation from a coming famine by sending Joseph to rule in Egypt. The failure of man in every circumstance is met by the salvation of God. We fail, but the good news is God saves us.',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-1500',
    End_Year: '',
    Headline: 'Exodus',
    Text: 'The book of Exodus is the second book of the Torah (“law”). It continues the story of Genesis concerning the migration of the family of Jacob (the Israelites) to Egypt (Genesis 50). It describes the commissioning of Moses and Aaron as God’s representatives on earth to accomplish God’s deliverance of His people from slavery in Egypt and lead them to the Promised Land (the land of Canaan). It also relates the miraculous deliverance from Egypt beginning with the plagues on Egypt and the crossing of the Red Sea. It then describes the journey to Mount Sinai and the establishment of the Mosaic covenant with the Israelites. The last part of the book involves the specifications and building of the tabernacle – the place where the Lord Himself dwelt amongst His people. In the book of Exodus, the focus shifts to the deliverance of God’s people.',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-1450',
    End_Year: '',
    Headline: 'Leviticus',
    Text: 'Leviticus is largely about directions for sacrificial ceremonies and worship, and might seem hard for the modern reader to relate to. However, the New Testament reveals the great extent to which the entire Tabernacle enterprise symbolizes eternal truths that are as relevant to the New Testament believer as to the Old.\nIn particular, the New Testament book of Hebrews says that all the Tabernacle items are copies of the real thing in heaven. It further discusses the meaning of the priesthood and sacrifices, all of which look forward to Jesus Christ’s ministry on behalf of a fallen race.',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-1467',
    End_Year: '',
    Headline: 'Numbers',
    Text: 'The book of Numbers is the fourth of the five books of Moses that comprise the Torah, which means “Law.” It gets its English name from the Greek Old Testament called the Septuagint (or LXX). The LXX named this book, “Arithmoi,” meaning “Numbers.” Its Hebrew name means “in the desert” or “in the wilderness.” Both names are appropriate. The Hebrew name is appropriate because Numbers covers the Israelites’ wanderings in the wilderness (or “desert”) from Sinai to the plains of Moab. The Greek name is also appropriate because of the many lists, and the numbers within those lists.\nAt the beginning of the book, the Israelites had been camped at Mount Sinai for about a year. The book of Exodus covered their escape from Egypt and their journey to Sinai. The LORD commanded Moses to organize the people in preparation to leave Sinai and go to the Promised Land. The book covers around 38 years of the Israelites’ journey from Egypt to the Promised Land, and describes many of Israel’s failures, including mutinies against Moses and outright disobedience to the word of the LORD. In Numbers, the LORD declares that the generation that left Egypt would die in the wilderness due to their disobedience. Only two, Joshua and Caleb, were allowed to enter the Promised Land, due to their faithfulness. Even Moses died without entering the Land due to disobedience.',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-1445',
    End_Year: '',
    Headline: 'Deuteronomy',
    Text: 'The book of Deuteronomy is the fifth and last book of the Torah (“law”). It continues the story of the first 4 books and picks up exactly where the book of Numbers ends (with the people on the plain of Moab). Therefore, as we set the context for the book of Deuteronomy, it is important that we briefly summarize the theme of the previous books to see how the story of God unfolds.\nGenesis describes God’s plan to bless the Israelites and the world through one man named Abraham (Gen. 12:1-3). Exodus focuses on God’s loving act by which He rescued the Israelites from Egypt in order to have a covenant relationship with them. Once the children of Israel are redeemed, Leviticus instructs them to live a holy life that reflects the life of their covenant redeemer (cf. Lev. 19). Since the first generation of the Israelites failed to obey God wholeheartedly, the book of Numbers displays a strong contrast between God’s faithfulness and the nation’s failure. That is why the book of Deuteronomy reiterates and expands on the covenant to a new generation of Israelites poised to enter and conquer the Promised Land. The message of the book is centered around two key terms: love and loyalty (Deut. 6:4-5).',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-1405',
    End_Year: '',
    Headline: 'Joshua',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-1043',
    End_Year: '',
    Headline: 'Judges',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-1030',
    End_Year: '',
    Headline: 'Ruth',
    Text: 'The book of Ruth follows the story of a Moabite woman named Ruth who marries an Israelite man who later dies, leaving her a widow with few resources. While the easy route would have been to return to her family and find a Moabite husband, Ruth commits to remain with her Israelite mother-in-law and joins her on the journey back to her home in Israel. Ruth is a model of courage and character, as she continually works to provide for herself and her mother-in-law. Boaz, a relation of Ruth’s late husband, enters the scene and provides for Ruth, taking note of her character and care for her mother-in-law.\nRuth is an incredible example to us as someone who forsook an old life for a new one, lived courageously and faithfully, and was greatly rewarded in the end.\nThe book of Ruth also presents the idea of a kinsman-redeemer, a close relative or relationship that is able to provide immense, immeasurable benefits to another person. Boaz serves as a kinsman-redeemer, and also sacrifices for the benefit of Ruth and her mother-in-law Naomi. Boaz and Ruth are both rewarded for their faithful service by being the great grandparents of King David. That places them in the direct lineage of  Jesus Christ, who serves as a kinsman-redeemer for all of mankind.\nRuth is ultimately an example of a godly wife (Ephesians 5:22-24) and also of the relationship all believers should have with Christ. She was virtuous and faithful while serving others. She was subject to Boaz and submitted herself to his leadership. Boaz also made a great sacrifice which provided immeasurable benefit to Ruth. This kind of marriage is a picture of our relationship with Christ. Christ is our leader and ultimately our redeemer and savior, who sacrificed himself for us. Our faithfulness to him is for our good. Just as Ruth’s sacrifices and faithfulness to Boaz resulted in him acting as her kinsman-redeemer and providing her great reward, so our faithfulness and submission to Christ will result in our reward (Revelation 3:21).',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-931',
    End_Year: '',
    Headline: '1 Samuel',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-900',
    End_Year: '',
    Headline: '2 Samuel',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-561',
    End_Year: '',
    Headline: '1 Kings',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-538',
    End_Year: '',
    Headline: '2 Kings',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-450',
    End_Year: '',
    Headline: 'Chronicles',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-430',
    End_Year: '',
    Headline: '2 Chronicles',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-457',
    End_Year: '',
    Headline: 'Ezra',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-424',
    End_Year: '',
    Headline: 'Nehemiah',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-450',
    End_Year: '',
    Headline: 'Esther',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-2000',
    End_Year: '',
    Headline: 'Job',
    Text: 'The Book of Job is the oldest book of the Bible. It predates the Israelites as well as the Patriarchs. Many of the Hebrew words in Job do not appear anywhere else in the Bible making it more difficult to translate.',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-1010',
    End_Year: '',
    Headline: 'Psalms',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-971',
    End_Year: '',
    Headline: 'Proverbs',
    Text: 'These are the proverbs of Solomon, one of the most renowned kings in the history of Israel. The word translated “proverb” is the Hebrew word “mashal.” The root of the word contains the idea of “compare”—it is translated throughout Scripture as “parable” just as often as “proverb.”\nThis gives us some insight into the nature of these sayings. Proverbs are not prescriptions. It is not about a formula for how to manipulate circumstances and bend them to our will. That might be wishful thinking, but doesn’t work in reality. The proverbs are, in a sense, “comparing” our human perceptions to the reality of God’s world; trying to connect the two by providing principles that shape our perspective and inform our choices such that we live constructively—that is to say, wisely.',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-940',
    End_Year: '',
    Headline: 'Ecclesiastes',
    Text: 'One of the most fascinating books of Scripture, Ecclesiastes sets out on a difficult but foundational task—reconciling the human longing to discover and understand, to find meaning and purpose, with the practical realities of being a finite creature in a world created by an infinite being. What is discovered is that human reason and experience is inadequate to find purpose. If we rely solely on human reason and experience, we only find futility and madness. However, if we begin with faith, we can effectively use our human faculties to realize wisdom and fulfillment.\nEcclesiastes predicts the failure of human philosophy to discover purpose apart from faith, while offering a viable philosophical solution: to begin with faith.\nThe author, Qoholeth in Hebrew, or “Assembler,” is trying to make sense of life “under the sun.” It is widely believed “Qoholeth” is King Solomon, renowned for his wisdom. His goal is to synthesize philosophy with the practical world around him.\nSolomon invites us on a great journey of discovery. If anyone could use reason to discover meaning through life experiences, it would be Solomon. Solomon’s great wealth meant he could use all his time toward his investigations. His unsurpassed wisdom allowed him the faculties to design a vast array of activities, as well as assess their results, and determine their meaning.\nSolomon’s conclusion is dark but real: neither meaning nor purpose can be discerned through human reason and experience. As the rivers flow endlessly to the sea, so one life flows to the next. Without a foundation of faith, life has no meaning.\nSolomon shares with us his experiments to find meaning through reason and experience. He tries achievement and engages in vast building projects. He tries every sort of pleasure and entertainment, spanning the full spectrum of wine, women, and song. He leaves no stone unturned, but finds nothing but futility. Solomon’s experience is summarized in one word: “hebel.” Hebel is Hebrew for “vaporous.” A fog, a mist. Something that is there but can’t be grasped. You see it for a moment, then it is gone. Such is a philosophy of life founded upon human reason and experience.\nEcclesiastes tackles the kinds of things we think about but do not often say. And likely do not wrestle with to the extent Solomon does. Utilizing a mix of imagery and direct description, the Book of Ecclesiastes is an honest attempt to reconcile life on this Earth with the mysteries of Heaven.\nEcclesiastes’s refusal to pull any punches has caused many to describe it as negative and depressing. But the truths discovered in this book are real. Reality might be an acquired taste, but Solomon urges us to see reality for what it is.\nWhen Solomon sees reality firsthand, it causes him to turn to God, and find fulfillment. Life can be confusing and complicated. It can seem like we are living in a fog. We cannot gain clarity through our own efforts and experiences. But clarity can come if our starting place is faith in God. Solomon concludes with an exhortation that life’s fulfillment is found in following God’s ways, for it is He who will determine the meaning of all deeds in His final judgement.\nThe patient, teachable reader will discover truth, hope, and challenge within these chapters. In the end, it is a strange joy only found through full consideration of the mysteries of God.',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-971',
    End_Year: '',
    Headline: 'Song of Solomon',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-700',
    End_Year: '',
    Headline: 'Isaiah',
    Text: 'The Book of Isaiah is the first and longest book of prophecy in the Bible. Its sixty-seven chapters make it the Bible’s second longest book after the Psalms. Isaiah’s message is one of the LORD’s justice and grace. Written 700 years before Christ, its prophecies concern the geopolitical events during the reign of King Hezekiah who was a contemporary of Isaiah, the Babylonian exile, Judah’s return, and the end times. The book of Isaiah also contains numerous prophecies about the Messiah’s birth, mission, character, suffering, and triumph.',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-586',
    End_Year: '',
    Headline: 'Jeremiah',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-587',
    End_Year: '',
    Headline: 'Lamentations',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-590',
    End_Year: '',
    Headline: 'Ezekiel',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-536',
    End_Year: '',
    Headline: 'Daniel',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-750',
    End_Year: '',
    Headline: 'Hosea',
    Text: 'The book of Hosea contrasts God’s faithfulness to Israel’s faithlessness. In the first three chapters, Hosea introduces the reader to Israel’s infidelity to their Suzerain (Ruler) God who entered into a covenant with Him, and spelled out the path they could take that would lead to great blessing. God’s covenant with Israel can be viewed as a marital contract. By using Hosea’s own marriage to his unfaithful wife, Gomer, God demonstrated that Israel is an unfaithful covenant partner. Israel had broken her vows to her Covenant Husband. Throughout the rest of Hosea, Israel’s condition is described as disobedient, rebellious, and idolatrous. As God had warned, Israel’s adoption of pagan principles of self-indulgence led to exploitation, deception, and violence (Hosea 4:2). The people of Israel stood in need of repentance and genuine righteousness. Hosea called them to repentance, but Israel declined.\nIsrael spent years sowing to its own destruction, making and breaking alliances with the world’s superpowers at the time, Egypt and Assyria, dealing treacherously. Hosea describes Israel as acting like a “silly dove” flitting from one nation to the other, rather than turning to God for protection (Hosea 7:11). Thus Assyria will come and put Israel into exile, which God will use as a way of punishing Israel for its infidelity to its covenant with God (Hosea 11:5). Through it all, however, the book offers hope to Israel. For although the Suzerain God invoked the discipline provisions of their covenant contract with Him, resulting in them being wounded grievously, in the end times He will heal them, revive them, and restore their blessings (Hosea 2:20, 14:7). May all who read this book find comfort and hope in the steadfast love and faithfulness of God!',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-835',
    End_Year: '',
    Headline: 'Joel',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-750',
    End_Year: '',
    Headline: 'Amos',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-850',
    End_Year: '',
    Headline: 'Obadiah',
    Text: 'The book of Obadiah bears the name of its author. The name Obadiah means “servant of Yahweh,” suggesting that the prophet was born and raised by godly parents. Obadiah mentioned no kings who ruled in his day. But the reference to the plundering of Jerusalem likely speaks of the city’s invasion either by the Philistines and the Arabian tribes around 845 BC (2 Chronicles 21:16–17) or by Babylon in 586 BC.\nIt seems better to go with the 845 BC date for at least three reasons. First, the Jews place the book between Amos and Jonah in the Hebrew canon, suggesting a preexilic date of writing. Second, the prophet Obadiah did not mention Babylon or the destruction of Jerusalem’s temple in 586 BC. Third, the prophet Jeremiah seems to quote from Obadiah (compare Jeremiah 49:14 with Obadiah 1:1, and Jeremiah 49:9 with Obadiah 1:5). Thus, it is likely that the prophecy of Obadiah was delivered around 845 BC.',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-775',
    End_Year: '',
    Headline: 'Jonah',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-735',
    End_Year: '',
    Headline: 'Micah',
    Text: 'The first verse of the book states that it was written by Micah who was from Moresheth (or Moresheth-Gath because of its nearness to the city of Gath), a town about 20 miles southwest of Jerusalem. Micah’s name means “who is like Yah[weh]” (the LORD). It is a question assuming the answer “no one,” emphasizing the uniqueness and sovereignty of the God of Israel, Yahweh. Micah prophesied mainly to the people of the Southern Kingdom (i.e., Judah). He knew that the morally corrupt and idolatrous Northern Kingdom of Israel (Samaria) would be destroyed by the Assyrians (1:6), which happened in 722 BC (1 Kings 17), years after Micah began his prophetic ministry. He used this predicted event to warn the Southern Kingdom of Judah that they could look forward to a similar fate if they did not turn from their own sinful ways. He voiced this message during the years following the fall of Israel in 722 BC, leading up to the Assyrian siege of Jerusalem in 701 BC. The LORD intervened and destroyed the Assyrian army, preserving Judah (2 Kings 19:32-36). Around a century later, however, Judah was taken into exile by the Babylonians (2 Kings 24 – 25).\n\n',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-650',
    End_Year: '',
    Headline: 'Nahum',
    Text: 'The prophet Nahum predicted judgment on Nineveh, the capital and strength of Assyria. About one hundred years earlier, the LORD had sent the prophet Jonah to preach a message of repentance to Nineveh. The people of Nineveh repented for a while but shortly after returned to their wickedness and cruelty. Now the LORD raised the prophet Nahum to announce the destruction of Nineveh. Nahum’s prophecy also offered hope and comfort for Judah, which the Assyrian empire had oppressed for so long (Nahum 1:15).',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-615',
    End_Year: '',
    Headline: 'Habakkuk',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-635',
    End_Year: '',
    Headline: 'Zephaniah',
    Text: 'Zephaniah prophesied during the reign of Josiah, king of Judah. He encouraged the people to return to God, honor the vows they made to God under their covenant with Him, and avoid the penalties associated with violating their vows. The message of Zephaniah complements that of the prophet Jeremiah. Both seek to encourage Judah to repent and return to their Suzerain (Ruler) God, and honor their covenant with Him, thus avoiding His day of wrath.\n\nKing Josiah reigned in Judah from 640 to 609 BC. The Babylonians placed Judah under servitude shortly after his death, in 605 BC, taking its then king Jehoiachin captive, and carrying off the treasures from the temple, along with many officials and soldiers. Judah rebelled again. In 586 BC, Jerusalem was destroyed and all but the poorest of the people were exiled.',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-520',
    End_Year: '',
    Headline: 'Haggai',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-480',
    End_Year: '',
    Headline: 'Zechariah',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-433',
    End_Year: '',
    Headline: 'Malachi',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
]
