export const oldTestamentEvents = [
  {
    Year: '',
    End_Year: '',
    Headline: 'Take a journey through the Biblical Timeline ',
    Text: 'Welcome to the TBS Timeline. Click the NEXT arrow to see the beginning of our timeline, the time of Adam which starts at 4000 BC est. Or you can click any event on the timeline to learn about it.',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: 'title',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-4000',
    End_Year: '',
    Headline: 'The First Adam',
    Text: 'God formed man from dust. God molded man like a potter molds clay. For instance, in the book of Job we see, Behold, I belong to God like you; I too have been formed out of the clay (Job 33:6).\nBut now, O LORD, You are our Father, We are the clay, and You our potter; And all of us are the work of Your hand (Isaiah 64:8). Then God breathed into man the breath of life, causing man to become alive. Man became a living being or soul.\nThe Scriptures tell us, ‘The first man, Adam, became a living person.’ But the last Adam—that is, Christ—is a life-giving Spirit (1 Corinthians 15:45). Although other living creatures possess life, only human life is linked to the breath of life given by God.\nGod specially prepared a garden in an area called Eden (commonly referred to as the Garden of Eden) and placed man in it. Eden was a place of delight and pleasure. It was a unique dwelling place furnished and adorned by nature. The stars of heaven formed its cathedral ceiling. The lights came on and turned off when they were supposed to, there was not a lock on a door. It truly was a paradise that provided Adam with everything he needed. It had beautiful trees that were good for food and it was a blessed place provided by God’s grace.',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/shutterstock_2043241274.jpg',
  },
  {
    Year: '-3870',
    End_Year: '',
    Headline: 'Seth is Born',
    Text: 'After Abel was murdered by his brother, Seth was born. When Adam was 130 years old, Seth was born in his likeness (just a God had made man in His likeness). Adam had other sons and daughters. It seems clear that the environment and the human body had major differences during this era. Psalm 90:10, written roughly three thousand years ago, says that life expectancy is seventy or eighty years, similar to what we experience today. But during the period of history prior to Noah’s flood things were very different.',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-3750',
    End_Year: '',
    Headline: 'Enosh is Born',
    Text: 'At 105 years of age, Seth had a son and named him Enosh, whose name means “human being.”',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-3660',
    End_Year: '',
    Headline: 'Kenan is Born',
    Text: 'Kenan was the father of Mahalalel.',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-3605',
    End_Year: '',
    Headline: 'Mahalalel is Born',
    Text: 'Mahalel was the father of Jared, who became the father of Enoch.',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-3540',
    End_Year: '',
    Headline: 'Jared is Born',
    Text: 'Jared was the father of Enoch.',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-3380',
    End_Year: '',
    Headline: 'Enoch is Born',
    Text: ' Enoch was the father of Methuselah. Enoch “walked with God” and is the first man to be translated directly to heaven without dying. \nWe see the redemptive branch of the human family tree continue. Mahalalel and Jared may not seem important in God’s story of salvation. But they are more than strange names in an ancient genealogy. They are part of God’s generational chain concluding with the birth of Jesus Christ. We can see this in Luke 3:37-38, where Jesus’ genealogy is traced all the way back to Adam.\nGenesis 5:22 says, Enoch walked with God. He had a special relationship with God. Enoch was a man of faith who obeyed God faithfully. Because of this, Enoch did not die physically. The author of Hebrews explains that it was By faith [that] Enoch was taken up so that he would not see death; and he was not found because God took him up for he obtained the witness that before his being taken up he was pleasing to God (Hebrews 11:5). Enoch was also vocal about his beliefs and relationship with God and warned those who pursued sin (Jude 1:14-16).',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-3310',
    End_Year: '',
    Headline: 'Methuselah is Born',
    Text: 'Methuselah lived a very long life of 969 years. He is the longest living person recorded in the Bible. Methuselah had Lamech who in turn had Noah.',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-3125',
    End_Year: '',
    Headline: 'Lamech is Born',
    Text: 'In Genesis 4 we learned that in the genealogy of Cain there was a man named Lamech (Genesis 4:18-24). Likewise, in the godly line of Seth, there was a Lamech, son of Methuselah. Although they had the same name, their family heritage impacted who they were and how they lived. Seth’s Lamech was the father of Noah, who was used by God to save the human race and continue the messianic promise. Cain’s Lamech murdered a young man who had wounded him and then boasted about it to his wives (Genesis 4:23-24). This shows the very different paths that these two families took.\nLamech’s hope for his son, Noah, is explained by Lamech in the naming, when Lamech prophesies that Noah will be the agent God will use to give humanity rest. This shows us that mankind still understood God’s curse and desired a form of relief from it.',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-3000',
    End_Year: '',
    Headline: 'The Birth of Noah',
    Text: 'Noah was a righteous man, meaning he was just man and spiritually upright. He was honorable and full of integrity. Just like Enoch, Noah walked with God, meaning he was obedient and faithful to Him. Noah was delivered from the flood, and Enoch was delivered from physical death. God delivers those who walk with Him. Noah was also given three sons, Shem, Ham, and Japheth. We are not told why Noah only has three children, and those coming between ages five hundred and six hundred. But it seems that child bearing was spaced much further apart during this era of human history.\nGod looked on the earth, and behold, it was corrupt, for all flesh had corrupted their way upon the earth. The wicked of the world sinned openly without shame, boldly without any fear of God. All mankind was marred and ruined. Men did what was right in their own eyes, but there is always a consequence for actions. The consequence for mankind becoming so corrupt was that God declared He would destroy from the face of the earth both man and beast. The flood was God’s judgment. God decided to destroy humanity and the earth as well. Then God said to Noah, “The end of all flesh has come before Me; for the earth is filled with violence because of them; and behold, I am about to destroy them with the earth.” Because of the corruption and violence on the earth, and the extent of it, God would judge the wicked along with the earth.\n',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/shutterstock_1326289805.jpg',
  },
  {
    Year: '-2450',
    End_Year: '',
    Headline: 'Shem is Born',
    Text: 'Noah had three sons: Shem, Ham, and Japheth. Shem and his wife were on the ark with Noah. After disembarking, Noah planted a vineyard and got drunk in his tent. \nHam walked into Noah’s tent and saw the nakedness of his father and told his two brothers outside. Shem and Japheth, in honor and respect of their father, went into his tent and covered the nakedness of their father. When Noah awoke and became sober, he gave a blessing and curse about the future of his three sons and their generations. For his obedience, Shem, the ancestor of the Israelites, was to be the master over Ham’s descendants, the Canaanites.\nNoah blessed (praised) the Lord instead of Shem because He is the source of Shem’s blessings, saying Blessed be the Lord, The God of Shem; And let Canaan be his servant. A blessing implies the inheritance of something good. One translator suggests, “May God bless the tents of Shem. The one and true living God shall be Shem’s God, and the knowledge and practice of faith will continue among his descendants. Shem is the one through whom the promised blessing will come to Abraham. God tells Abraham, “all peoples on earth will be blessed through you” (Genesis 12:3). It is through the line of Shem the Messiah will be born.',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-2350',
    End_Year: '',
    Headline: 'The Great Flood',
    Text: "God looked on the earth, and behold, it was corrupt, for all flesh had corrupted their way upon the earth. The wicked of the world sinned openly without shame, boldly without any fear of God. All mankind was marred and ruined. Men did what was right in their own eyes, but, as always, there are consequences for actions. The consequence for mankind becoming so corrupt was that God declared He would destroy from the face of the earth both man and beast. The flood was God’s judgment. God decided to destroy humanity and the earth as well. However, one man - Noah - found favor in God's eyes and was instructed to build an ark to save himself and his family from the flood. \nAfter entering the ark as God had commanded him, God closed the door of the ark behind him. Noah and his family with all the inhabitants were safe and secure inside the ark, where they spent over one year. Then the flood came upon the earth forty days. The raging rain lasted on the earth for forty days and nights. However, the flood waters continued for one hundred and ten days. The waters did not merely rise, the flood was violent and mighty, overwhelming the earth. Whole mountain ranges were covered by the water. In fact, all the high mountains everywhere under the heavens were covered with water. The flood water was on the earth one hundred and fifty days, or five months, before the waters began to recede.\n",
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/shutterstock_1326289805.jpg',
  },
  {
    Year: '-2270',
    End_Year: '',
    Headline: 'Tower of Babel',
    Text: 'In disobedience to God’s command to fill the earth (Genesis 9:1), the people, all sharing one language, decided to settle and build a city; they found a plain in the land of Shinar. The people had two goals, to build for ourselves a city, and to build a tower whose top will reach into heaven. It appears the tower is an essential part of the object of building a city and a tower, namely to make for ourselves a name. Current historical and archeological evidence shows the Tower of Babel was most likely located at Eridu in Mesopotamia. Mankind was in defiance of God’s will that the entire earth should be populated. If left unchecked, they would undertake more deeds of evil and defiance. So, God confused their language so that they will not understand one another’s speech and scattered them abroad from there over the face of the whole earth; and they stopped building the city. The confusion of language occurred in the fourth generation after the flood, about the time of the birth of Peleg (Genesis 10:25). ',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-1950',
    End_Year: '',
    Headline: 'Isaac is Born',
    Text: 'Isaac was born exactly when God said he would be. A year prior, God visited Abraham’s camp and promised they would have a son. Sarah doubted the promise that she would have a child at her age, laughing. God responded to her, saying, “Is anything too difficult for the Lord? At the appointed time I will return to you, at this time next year, and Sarah will have a son” (Genesis 18:14). Just as God said, Isaac was born a year later. Abraham called the name of his son…Isaac, in obedience to God (Genesis 17:17-19). The name Isaac in Hebrew is Yitzhak and means “he laughs” or “laughter.” This was because Abraham laughed when God told him he would have a son with his wife, just as she laughed when she learned the same promise. It seemed preposterous that they would ever have children, especially now that they were very old. Yet their laughter, once doubtful, becomes the laughter of joy at finally having a child together. Isaac was the promised son and heir of Abraham. Through Isaac, God would bless the nations and keep His covenant and promises to Abraham (Genesis 21:8-10, 25:1-6). This was the second time Abraham proclaims the name of his baby, the first being Ishmael, and now Isaac (Genesis 16:15). The name Isaac was God’s choice of naming the child Abraham had fathered by Sarah. Isaac’s name was given by God before he was even conceived (Genesis 17:19).',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-2000',
    End_Year: '',
    Headline: 'Abraham',
    Text: 'God called Abraham from a pagan world to begin a new nation. God instructed Abram to Go forth from your country and from your relatives and from your father’s house. At that point they dwelt in the city of Haran, not to be confused with Abram’s deceased brother of the same name. Abram’s Father Terah had led them out of Ur to settle in Haran, where Terah lived until his death. Now God gave a command: go forth.',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-1700',
    End_Year: '',
    Headline: 'Jacob and Sons Go to Egypt',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-1570',
    End_Year: '',
    Headline: 'Moses is Born',
    Text: "Moses’ parent's names are given in Exodus 6:20 and Numbers 26:59 as “Jochebed” (which means “the LORD is glory”) for his mother and “Amram” (which probably means “exalted people”) for his father. The result of the union is that the woman conceived and bore a son. Pharaoh’s plan was to have this child killed. It is likely that many Hebrew male babies were killed as a result of Pharaoh’s decree. This surely troubled the mother when she saw that he was beautiful. To say that he was beautiful (Hebrew “good”) probably means that he was a happy, healthy child. In Acts 7:20, Stephen said that Moses was “lovely in the sight of God”. The Hebrew phrase is also similar to what is seen in the creation narrative when it says that “God saw . . . that it was good” (Genesis 1:4 et al). It could also mean that the mother saw in him something special beyond his physical appearance.",
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-1500',
    End_Year: '',
    Headline: 'Exodus From Egypt',
    Text: 'How were the Israelites guided out of Egypt? The Lord was going before them in a pillar of cloud by day to lead them on the way, and in a pillar of fire by night to give them light. The one pillar changed from smoke during the day to fire during the night. Not only did it lead Israel on its journey, it enabled them to travel by day and by night. It also might have been large enough to provide shade in the daytime and light when it was dark. It was also a constant presence, because He did not take away the pillar of cloud by day, nor the pillar of fire by night, from before the people. This became a symbol of the LORD’s abiding presence with His people. They could rely on His leadership, and it was in their best interest to obey and follow Him. The pillar was a visible confirmation of the constant presence of the LORD. The presence of the LORD meant that the Israelites were always led in the right direction and unceasingly protected as they travelled.',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBGMoses-scaled.jpg',
  },
  {
    Year: '-1020',
    End_Year: '',
    Headline: 'King David',
    Text: 'In 1 Samuel 16:12 Jesse sent and brought David in. The fact that they brought David in would infer that this is taking place inside a dwelling. Perhaps Samuel is being hosted in Jesse’s home. The narrative now describes what Samuel saw when he observed David. Now he was ruddy, with beautiful eyes and a handsome appearance. The Hebrew word for ruddy is “edomi” which means “red one.” A title also given to Esau as “Edom.” This indicates that David possibly had red hair or a reddish complexion. God says to Samuel, “Arise, anoint him; for this is he.” Once again, we are told Samuel’s inner thoughts, and the voice he is hearing from God. Samuel obeyed immediately upon God’s direction. Then Samuel took the horn of oil and anointed him in the midst of his brothers. When David’s brothers saw that he was chosen instead of them it probably created a sort of animosity in them towards David.',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/david-scaled.jpg',
  },
  {
    Year: '-990',
    End_Year: '',
    Headline: 'King Solomon',
    Text: 'The beginning of Solomon’s reign was the height of the Jewish Nation’s political strength. Israel, its land, and alliances became the center of civilization during Solomon’s reign. Solomon writes the book of Ecclesiastes as the King, a position of maximum authority at this time of Jewish prosperity. The investigations Solomon is about to recount will cover the entire range of human experience, including labor, relationships, agricultural and architectural pursuits, intellectual considerations, ruling and living in a kingdom. His role as King puts him in a position to have the experience necessary for this endeavor. Solomon is historically renowned for wisdom. With all things offered to him by God, he asks for and is granted wisdom (2 Chronicles 1:7-12; 1 Kings 3). The Book of Ecclesiastes describes his journey in living with wisdom and exploring its effect. He is uniquely equipped for the discussion to come. He uniquely has the wealth, time, position, intellect, and insight to engage such an ambitious pursuit and find its conclusion.',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-970',
    End_Year: '',
    Headline: 'King Rehoboam',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-940',
    End_Year: '',
    Headline: 'King Abijah',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-920',
    End_Year: '',
    Headline: 'King Asa',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-900',
    End_Year: '',
    Headline: 'King Jehoshaphat',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-860',
    End_Year: '',
    Headline: 'King Jehoram',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-810',
    End_Year: '',
    Headline: 'King Uzziah',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
  {
    Year: '-725',
    End_Year: '',
    Headline: 'Assyrian Siege of Jerusalem',
    Text: 'Now in the fourteenth year of King Hezekiah, Sennacherib king of Assyria came up against all the fortified cities of Judah and seized them (vs 1). This follows Assyria’s assault and conquering of Samaria seven years earlier. Samaria was the capital of the northern kingdom of Israel. Israel and Judah had split in the reign of Solomon’s son Rehoboam (1 Kings 12:16-17).\nIn the fourth year of Hezekiah’s being king of Judah, Assyria came to besiege Samaria. At this point in history Assyria was a powerful empire. The siege and exile of Israel by Assyria transpired in 725-722 BC. Assyria trounced Samaria, ending a three-year siege. The northern kingdom’s “ten lost tribes” of Israel, as they are now called, never returned (except perhaps since 1948 AD in our modern era).\nAfter Assyria had defeated the northern kingdom, they came with the intent to defeat Judah. But unlike with Israel, God intervenes to save the southern kingdom of Judah. Assyria had already taken all the fortified cities of Judah but one: Jerusalem (vs 1). Seven years after Hezekiah had watched Samaria fall, Assyria was now at his doorstep. This was, in part, because Hezekiah rebelled against the king of Assyria by not paying tribute or taxes (2 Kings 18:7).\nThe Samaritans of the New Testament were descendants of the few remaining Israelites in the northern kingdom, who intermarried with the Assyrians (or others). They were despised by the Jews from Judah as a result, which carried into the time of the New Testament.\n',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/Roberts_Siege_and_Destruction_of_Jerusalem.jpeg',
  },
  {
    Year: '-586',
    End_Year: '',
    Headline: 'Babylonian Exile Begins',
    Text: 'Jerusalem was put under siege by the Babylonians and destroyed in 586 BC. Many of its inhabitants died, and many were taken to Babylon.',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/Roberts_Siege_and_Destruction_of_Jerusalem.jpeg',
  },
  {
    Year: '-331',
    End_Year: '',
    Headline: 'Alexander the Great is defeated',
    Text: '',
    Media: '',
    Media_Credit: '',
    Media_Caption: '',
    Media_Thumbnail: '',
    Type: '',
    Background:
      'https://thebiblesays.com/wp-content/uploads/2022/05/TimelineBG-scaled.jpg',
  },
]
